### ISSUE TITLE
Grad der Behinderung: Welcher SnomedCT Code?

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/TC-Terminologie#3]
Aktuell angedacht:
246464006:704326004=21134002

Besprochen im TC FHIR: https://docs.google.com/document/d/10Lpoier8jektLdqVf7FQ_a8zTeDtwaa43Xa-KK0MFqY/edit

Frage aus commiters(de) (oder dach) stream

**Comment by patrick-werner** [comment]
Bedenken: Code ist ein Finding und keine Observable Entity: "Ist Antwort und nicht die Frage".

- [ ] Weiterreichen der Frage an national Releasecenter (bfarm)

weiterer Kandidat: 21134002 Disability percentage (finding)

**Comment by alexzautke** [comment]
https://www.bfarm.de/DE/Kodiersysteme/Terminologien/SNOMED-CT/_node.html

Anfragen zur Nutzung von SNOMED CT stellen
Das BfArM baut das NRC schrittweise auf. Wir werden den Einsatz und die Verbreitung von SNOMED CT gemäß unseren Kapazitäten unterstützen.

Wenn Sie eine Frage zu SNOMED CT bzw. einen Wunsch an das National Release Center beim BfArM haben, senden Sie bitte eine E-Mail an snomed@bfarm.de .

**Comment by alexzautke** [comment]
@marryah Stellt Anfrage bzgl. Kodierung ans BfArM
@simoneOnFhir Fragt in Zulip nach ob dies als Observation abgebildet werden sollte

**Comment by simoneOnFhir** [comment]
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/SNOMED.20findings.20in.20Observation.2Ecode

**Comment by patrick-werner** [comment]
Grahame bestätigte auf zulip die Verwendung dieses codes.
